name: "ensemble-model"
platform: "ensemble"
input {
  name: "user_id_raw"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
output {
  name: "ordered_ids"
  data_type: TYPE_INT32
  dims: -1
  dims: -1
}
ensemble_scheduling {
  step {
    model_name: "0-query-user-features"
    model_version: -1
    input_map {
      key: "user_id_raw"
      value: "user_id_raw"
    }
    output_map {
      key: "user_age"
      value: "user_age_0"
    }
    output_map {
      key: "user_brands"
      value: "user_brands_0"
    }
    output_map {
      key: "user_categories"
      value: "user_categories_0"
    }
    output_map {
      key: "user_consumption_2"
      value: "user_consumption_2_0"
    }
    output_map {
      key: "user_gender"
      value: "user_gender_0"
    }
    output_map {
      key: "user_geography"
      value: "user_geography_0"
    }
    output_map {
      key: "user_group"
      value: "user_group_0"
    }
    output_map {
      key: "user_id"
      value: "user_id_0"
    }
    output_map {
      key: "user_intentions"
      value: "user_intentions_0"
    }
    output_map {
      key: "user_is_occupied"
      value: "user_is_occupied_0"
    }
    output_map {
      key: "user_profile"
      value: "user_profile_0"
    }
    output_map {
      key: "user_shops"
      value: "user_shops_0"
    }
  }
  step {
    model_name: "1-user-embeddings"
    model_version: -1
    input_map {
      key: "user_age"
      value: "user_age_0"
    }
    input_map {
      key: "user_brands"
      value: "user_brands_0"
    }
    input_map {
      key: "user_categories"
      value: "user_categories_0"
    }
    input_map {
      key: "user_consumption_2"
      value: "user_consumption_2_0"
    }
    input_map {
      key: "user_gender"
      value: "user_gender_0"
    }
    input_map {
      key: "user_geography"
      value: "user_geography_0"
    }
    input_map {
      key: "user_group"
      value: "user_group_0"
    }
    input_map {
      key: "user_id"
      value: "user_id_0"
    }
    input_map {
      key: "user_intentions"
      value: "user_intentions_0"
    }
    input_map {
      key: "user_is_occupied"
      value: "user_is_occupied_0"
    }
    input_map {
      key: "user_profile"
      value: "user_profile_0"
    }
    input_map {
      key: "user_shops"
      value: "user_shops_0"
    }
    output_map {
      key: "output_1"
      value: "output_1_1"
    }
  }
  step {
    model_name: "2-redis-vss-candidates"
    model_version: -1
    input_map {
      key: "output_1"
      value: "output_1_1"
    }
    output_map {
      key: "candidate_ids"
      value: "candidate_ids_2"
    }
  }
  step {
    model_name: "3-query-item-features"
    model_version: -1
    input_map {
      key: "candidate_ids"
      value: "candidate_ids_2"
    }
    output_map {
      key: "item_brand"
      value: "item_brand_3"
    }
    output_map {
      key: "item_category"
      value: "item_category_3"
    }
    output_map {
      key: "item_id"
      value: "item_id_3"
    }
    output_map {
      key: "item_id_raw"
      value: "item_id_raw_3"
    }
    output_map {
      key: "item_shop"
      value: "item_shop_3"
    }
  }
  step {
    model_name: "4-unroll-features"
    model_version: -1
    input_map {
      key: "item_brand"
      value: "item_brand_3"
    }
    input_map {
      key: "item_category"
      value: "item_category_3"
    }
    input_map {
      key: "item_id"
      value: "item_id_3"
    }
    input_map {
      key: "item_id_raw"
      value: "item_id_raw_3"
    }
    input_map {
      key: "item_shop"
      value: "item_shop_3"
    }
    input_map {
      key: "user_age"
      value: "user_age_0"
    }
    input_map {
      key: "user_brands"
      value: "user_brands_0"
    }
    input_map {
      key: "user_categories"
      value: "user_categories_0"
    }
    input_map {
      key: "user_consumption_2"
      value: "user_consumption_2_0"
    }
    input_map {
      key: "user_gender"
      value: "user_gender_0"
    }
    input_map {
      key: "user_geography"
      value: "user_geography_0"
    }
    input_map {
      key: "user_group"
      value: "user_group_0"
    }
    input_map {
      key: "user_id"
      value: "user_id_0"
    }
    input_map {
      key: "user_intentions"
      value: "user_intentions_0"
    }
    input_map {
      key: "user_is_occupied"
      value: "user_is_occupied_0"
    }
    input_map {
      key: "user_profile"
      value: "user_profile_0"
    }
    input_map {
      key: "user_shops"
      value: "user_shops_0"
    }
    output_map {
      key: "item_brand"
      value: "item_brand_4"
    }
    output_map {
      key: "item_category"
      value: "item_category_4"
    }
    output_map {
      key: "item_id"
      value: "item_id_4"
    }
    output_map {
      key: "item_id_raw"
      value: "item_id_raw_4"
    }
    output_map {
      key: "item_shop"
      value: "item_shop_4"
    }
    output_map {
      key: "user_age"
      value: "user_age_4"
    }
    output_map {
      key: "user_brands"
      value: "user_brands_4"
    }
    output_map {
      key: "user_categories"
      value: "user_categories_4"
    }
    output_map {
      key: "user_consumption_2"
      value: "user_consumption_2_4"
    }
    output_map {
      key: "user_gender"
      value: "user_gender_4"
    }
    output_map {
      key: "user_geography"
      value: "user_geography_4"
    }
    output_map {
      key: "user_group"
      value: "user_group_4"
    }
    output_map {
      key: "user_id"
      value: "user_id_4"
    }
    output_map {
      key: "user_intentions"
      value: "user_intentions_4"
    }
    output_map {
      key: "user_is_occupied"
      value: "user_is_occupied_4"
    }
    output_map {
      key: "user_profile"
      value: "user_profile_4"
    }
    output_map {
      key: "user_shops"
      value: "user_shops_4"
    }
  }
  step {
    model_name: "5-ranking"
    model_version: -1
    input_map {
      key: "item_brand"
      value: "item_brand_4"
    }
    input_map {
      key: "item_category"
      value: "item_category_4"
    }
    input_map {
      key: "item_id"
      value: "item_id_4"
    }
    input_map {
      key: "item_id_raw"
      value: "item_id_raw_4"
    }
    input_map {
      key: "item_shop"
      value: "item_shop_4"
    }
    input_map {
      key: "user_age"
      value: "user_age_4"
    }
    input_map {
      key: "user_brands"
      value: "user_brands_4"
    }
    input_map {
      key: "user_categories"
      value: "user_categories_4"
    }
    input_map {
      key: "user_consumption_2"
      value: "user_consumption_2_4"
    }
    input_map {
      key: "user_gender"
      value: "user_gender_4"
    }
    input_map {
      key: "user_geography"
      value: "user_geography_4"
    }
    input_map {
      key: "user_group"
      value: "user_group_4"
    }
    input_map {
      key: "user_id"
      value: "user_id_4"
    }
    input_map {
      key: "user_id_raw"
      value: "user_id_raw"
    }
    input_map {
      key: "user_intentions"
      value: "user_intentions_4"
    }
    input_map {
      key: "user_is_occupied"
      value: "user_is_occupied_4"
    }
    input_map {
      key: "user_profile"
      value: "user_profile_4"
    }
    input_map {
      key: "user_shops"
      value: "user_shops_4"
    }
    output_map {
      key: "click/binary_classification_task"
      value: "click/binary_classification_task_5"
    }
  }
  step {
    model_name: "6-softmax-sampling"
    model_version: -1
    input_map {
      key: "click/binary_classification_task"
      value: "click/binary_classification_task_5"
    }
    input_map {
      key: "item_id_raw"
      value: "item_id_raw_4"
    }
    output_map {
      key: "ordered_ids"
      value: "ordered_ids"
    }
  }
}