name: "0-query-user-features"
backend: "python"
max_batch_size: 256
input [
{
    name: "input__0"
    data_type: TYPE_INT32
    dims: [ 1 ]
}
]
output [
{
    name: "output__0"
    data_type: TYPE_INT32
    dims: [ 12 ]
}
]
instance_group [{ kind: KIND_GPU }]